#ifndef COMMUNICADO_TFTPACK_CONSTANTS_H_
#define COMMUNICADO_TFTPACK_CONSTANTS_H_

#include <stdint.h>

#define TFTP_OP_RRQ (UINT16_C(1))
#define TFTP_OP_WRQ (UINT16_C(2))
#define TFTP_OP_DATA (UINT16_C(3))
#define TFTP_OP_ACK (UINT16_C(4))
#define TFTP_OP_ERROR (UINT16_C(5))

#endif /* COMMUNICADO_TFTPACK_CONSTANTS_H_ */
